### ISSUE TITLE
if file name has Non-ASCII Characters,  ipfs add would upload the wrong name

### ISSUE THREAD

**Issue by qiwaa** [ipfs-shipyard/java-ipfs-http-client#111]
the wrong result example:
https://ipfs.io/ipfs/QmZCvCp63opNvthopsfHJWPQb3S1JWExL6uD2besbqyE7W
the right result example:
https://ipfs.io/ipfs/QmPc93VJ1EfT6Qjc2P3ACmV8B2QhsFtynboNDP2fmCE48C

**Comment by kevodwyer** [comment]
Keeping open as it is an issue yet to be resolved

**Comment by kevodwyer** [comment]
resolved in: https://github.com/ipfs-shipyard/java-ipfs-http-client/pull/207
