### ISSUE TITLE
On android devices,the file copying of command “ipfs add” leads oom exception

### ISSUE THREAD

**Issue by Hermes001** [ipfs-shipyard/java-ipfs-http-client#129]
When i added only one 2.3GB file, my app‘s memory footprint reached over 1GB, than my app crash and throw "java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available".I want to know whether I can set the memory footprint of the process or not, I need to add large files.

**Comment by ZizhanChen** [comment]
@Hermes001 
Hey! It seems that you have implemented the app on your android device, I was wondering if you could teach me how to install the ipfs on android mobile phone?

**Comment by KebAz** [comment]
Hi @Hermes001 , I want also to integrate ipfs in my android app. Could you please recommend a link or a tutorial to do that?
Thanks.
