### ISSUE TITLE
Problems with IPFS add in latest version.

### ISSUE THREAD

**Issue by bragaz** [ipfs-shipyard/java-ipfs-http-client#132]
While i'm using add() method to store file into IPFS with v1.2.3 i get the following error:
`Server returned status: 404 with body:  and Trailer header: null`,
 i've tried to look for this problem online but seem to be no answer to this except one issue here from 2016 but it didn't enlighten me on a solution.
Anyone know how to fix this?
Thanks in advance.

**Comment by arashkahbasi** [comment]
Same problem here
I have not found any solution to this in code but I tried the IPFS api itself with cURL like this:
curl -X POST -F file=@myfile "https://127.0.0.1:8080/api/v0/tar/add" 
through the gateway port (8080) and received the same 404 response
Although when I tried it through the API port (5001) like this: 
curl -X POST -F file=@myfile "https://127.0.0.1:5001/api/v0/tar/add"
I get this message: 
{
  "Message": "unexpected EOF",
  "Code": 0,
  "Type": "error"
}

@bragaz Can you help me if you have found any answer to this?

**Comment by kevodwyer** [comment]
Closing as client library has seen updates since 2019. Feel free to re-open if still an issue.
