### ISSUE TITLE
[help wanted]difference between "public ByteArrayWrapper(byte[] data)" and "public ByteArrayWrapper(String name, byte[] data)"

### ISSUE THREAD

**Issue by CoreyLin** [ipfs-shipyard/java-ipfs-http-client#134]
I noticed that ByteArrayWrapper has three constructors, two of which take "name" as the first argument, so what does "name" mean from IPFS business point of view? In other words, before calling ipfs.add, what's the difference between "public ByteArrayWrapper(byte[] data)" and "public ByteArrayWrapper(String name, byte[] data)"? Thanks very much!

**Comment by odisseus** [comment]
This constructor allows you to construct a `NamedStreamable` that looks like a file (complete with a file name) without accessing the file system. If this "file" gets added into IPFS as part of a `DirWrapper` (which doesn't have to correspond to a real directory either), its name will be stored in the data block.
