### ISSUE TITLE
Unknown Codec type: 120

### ISSUE THREAD

**Issue by Bertrandbenj** [ipfs-shipyard/java-ipfs-http-client#139]
The following code 

```
        try {
            IPFS ipfs = new IPFS(new MultiAddress("/ip4/127.0.0.1/tcp/5001"));
            ipfs.refs.local();
            LOG.info("IPFS ");

        } catch (IOException e) {
            LOG.error("IPFS ", e);
        }

```

produces the following stack trace 

> 
> Caused by: java.lang.IllegalStateException: Unknown Codec type: 120
> 	at io.ipfs.cid.Cid$Codec.lookup(Cid.java:44)
> 	at io.ipfs.cid.Cid.cast(Cid.java:163)
> 	at io.ipfs.cid.Cid.decode(Cid.java:144)

on

 `            ipfs.refs.local();`

Libraries seems added properly

**Comment by kevodwyer** [comment]
Previous issues with dependencies should be resolved with latest release. Closing issue, feel free to re-open if required.
