### ISSUE TITLE
NullPointerException when incorrect SSL flag is set to IPFS constructor

### ISSUE THREAD

**Issue by vsbogd** [ipfs-shipyard/java-ipfs-http-client#142]
I am trying to create IPFS instance using `IPFS(String host, int port, String version, boolean ssl)` constructor. When I use incorrect value of `ssl` flag (`true` instead of `false`) constructor throws misleading `NullPointerException` instead of `IOException`. I use version `1.2.3`.

**Comment by gjeanmart** [comment]
Fixed in PR #148
