### ISSUE TITLE
jar包问题导致产生文件的hash不一致

### ISSUE THREAD

**Issue by iamxwts** [ipfs-shipyard/java-ipfs-http-client#143]
单层文件测试
linux
QmWYddCPs7uR9EvHNCZzpguVFVNfHc6aM3hPVzPdAEESMc test/1
QmT9SanPHnSH5AsBqy2xZbstw4rAw5znFPkmjkvDCMdVuF test/2
QmY4ZaCGXPTqRmTVEGSC6PPMgniAhMD1wPBTH7PeU3qtAf test/3
QmWqWDjT7xKR2z89nbeF8TL7fYi8jMrv3DNvPwgoQWe5gn test/4
QmWs25BiwkkgEEp7mx5dZ6dhE9ZyfMnhgUrwKKPpDPJkGJ test/5
Qmejxzx6Bs8h8Pjm17VWTHb5MWt98SXBCVD6MjfbJgKzEZ test

java-ipfs-api.jar
QmWYddCPs7uR9EvHNCZzpguVFVNfHc6aM3hPVzPdAEESMc test1
QmT9SanPHnSH5AsBqy2xZbstw4rAw5znFPkmjkvDCMdVuF test2
QmY4ZaCGXPTqRmTVEGSC6PPMgniAhMD1wPBTH7PeU3qtAf test3
QmWqWDjT7xKR2z89nbeF8TL7fYi8jMrv3DNvPwgoQWe5gn test4
QmWs25BiwkkgEEp7mx5dZ6dhE9ZyfMnhgUrwKKPpDPJkGJ test5
QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn test

java-ipfs-api-v1.2.2.jar
QmWYddCPs7uR9EvHNCZzpguVFVNfHc6aM3hPVzPdAEESMc test/1
QmT9SanPHnSH5AsBqy2xZbstw4rAw5znFPkmjkvDCMdVuF test/2
QmY4ZaCGXPTqRmTVEGSC6PPMgniAhMD1wPBTH7PeU3qtAf test/3
QmWqWDjT7xKR2z89nbeF8TL7fYi8jMrv3DNvPwgoQWe5gn test/4
QmWs25BiwkkgEEp7mx5dZ6dhE9ZyfMnhgUrwKKPpDPJkGJ test/5
Qmejxzx6Bs8h8Pjm17VWTHb5MWt98SXBCVD6MjfbJgKzEZ test

多层文件测试
linux
added QmWYddCPs7uR9EvHNCZzpguVFVNfHc6aM3hPVzPdAEESMc test/1	
added QmT9SanPHnSH5AsBqy2xZbstw4rAw5znFPkmjkvDCMdVuF test/2	
added QmY4ZaCGXPTqRmTVEGSC6PPMgniAhMD1wPBTH7PeU3qtAf test/3	
added QmWqWDjT7xKR2z89nbeF8TL7fYi8jMrv3DNvPwgoQWe5gn test/erjimulu/4	
added QmWs25BiwkkgEEp7mx5dZ6dhE9ZyfMnhgUrwKKPpDPJkGJ test/erjimulu/5	
added QmXcnJKMXD4PvocZCtSRMj8HuhY1r3sCyytBy83XmFpgsa test/erjimulu
added QmWoXPSemjajGEDVdyGnHREh28zRJpUKSW1tuAHQC86vKz test

java-ipfs-api.jar
QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn test
QmWYddCPs7uR9EvHNCZzpguVFVNfHc6aM3hPVzPdAEESMc test/1	
QmT9SanPHnSH5AsBqy2xZbstw4rAw5znFPkmjkvDCMdVuF test/2
QmY4ZaCGXPTqRmTVEGSC6PPMgniAhMD1wPBTH7PeU3qtAf test/3
QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn test/erjimulu
QmWqWDjT7xKR2z89nbeF8TL7fYi8jMrv3DNvPwgoQWe5gn test/erjimulu/4	
QmWs25BiwkkgEEp7mx5dZ6dhE9ZyfMnhgUrwKKPpDPJkGJ test/erjimulu/5	

java-ipfs-api-v1.2.2.jar
QmWYddCPs7uR9EvHNCZzpguVFVNfHc6aM3hPVzPdAEESMc test/1	
QmT9SanPHnSH5AsBqy2xZbstw4rAw5znFPkmjkvDCMdVuF test/2	
QmY4ZaCGXPTqRmTVEGSC6PPMgniAhMD1wPBTH7PeU3qtAf test/3	
QmZC8RXY7gKMzGEKF2iaAJVFS628qghwyK64UVLvG3qUN5 test
QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn test/erjimulu
QmWqWDjT7xKR2z89nbeF8TL7fYi8jMrv3DNvPwgoQWe5gn test/erjimulu/4	
QmWs25BiwkkgEEp7mx5dZ6dhE9ZyfMnhgUrwKKPpDPJkGJ test/erjimulu/5	
QmXcnJKMXD4PvocZCtSRMj8HuhY1r3sCyytBy83XmFpgsa test/erjimulu
QmbBs5RZxxuBTfbcvDp4kz2kZJwVt9B2XFvc58mpWh4jwU test

可进行参照，如果采用该jar包，无法在ipfs系统中查找到，非目录产的的hash一致，但是文件夹的长生了问题，请问如何解决

**Comment by Jaredjin** [comment]
这个和Jar包没关系，你直接用api试也是一样的，文件夹是造出来的空node

**Comment by kevodwyer** [comment]
closing as stale, free free to re-open and provide more information if required
