### ISSUE TITLE
Method retrieveStream of IPFS class has hardcoded "http"

### ISSUE THREAD

**Issue by josdam** [ipfs-shipyard/java-ipfs-http-client#144]
Class: IPFS.java 

Current private method:
private InputStream retrieveStream(String path) throws IOException {
        URL target = new URL(**"http"**, host, port, version + path);
        return IPFS.getStream(target);
    }

It should be
 private InputStream retrieveStream(String path) throws IOException {
        URL target = new URL(**protocol**, host, port, version + path);
        return IPFS.getStream(target);
    }

Otherwise retrieve from HTTPS is not possible

**Comment by gjeanmart** [comment]
Fixed in PR #149
