### ISSUE TITLE
java: cannot access io.ipfs.multiaddr.MultiAddress

### ISSUE THREAD

**Issue by Bme-Adib** [ipfs-shipyard/java-ipfs-http-client#151]
I Started the Daemon and I added the Jar file and the zip files to the library
But when ever i execute the Application this message shows up 

Error:(20, 16) java: cannot access io.ipfs.multiaddr.MultiAddress
  class file for io.ipfs.multiaddr.MultiAddress not found

can you help me please?

**Comment by odisseus** [comment]
Looks like you're missing some dependencies of this library. Make sure that `multiaddr.jar` is present in your classpath.
