### ISSUE TITLE
Missing contributing guidelines

### ISSUE THREAD

**Issue by iandinwoodie** [ipfs-shipyard/java-ipfs-http-client#152]
The link to the contributing guidelines (https://github.com/ipfs/community/blob/master/contributing.md) provided at line 114 of `README.md` (as of commit 146fa5d9ef4a595e2421eb11765053c3d846e6ad) is invalid. No file `contributing.md` exists in the repository.

**Comment by kevodwyer** [comment]
fixed and merged
