### ISSUE TITLE
Shall move to IPFS Shipyard org?

### ISSUE THREAD

**Issue by hsanjuan** [ipfs-shipyard/java-ipfs-http-client#155]
I am not sure how active this project is, but I see the issue tracker might use some triaging.

In any case, if this is not actively maintained, I'd like to move it to the ipfs-shipyard org, as it may be a better place.

Thoughts? I will proceed with this if no-one reacts in a couple of weeks.

**Comment by hsanjuan** [comment]
/remind me to circle back in 2 weeks.

**Comment by ianopolous** [comment]
Hi @hsanjuan, I'm the author of this and yes my spare time is limited these days. However, I could devote the time to update this to the latest APIs in ipfs and incorporate what we've learned from using it in Peergos over the years. Would Protocol Labs be interested in sponsoring this work? @momack2

**Comment by momack2** [comment]
Thanks for the suggestion! Is this on the order of magnitude of a bounty or devgrant (https://github.com/ipfs/devgrants)? There is significant interest from folks in Android-compatible APIs for IPFS - are there useful tweaks we could add with that in mind?

Note - we're releasing ipfs 0.5.0 in the next few weeks, so probably best to wait for those changes before bubbling things up...
