### ISSUE TITLE
Can't wrap files in directory when uploading in Windows

### ISSUE THREAD

**Issue by bobbyharsono** [ipfs-shipyard/java-ipfs-http-client#156]
I'm using:
- Window 10
- Java 8

Chronology:
I tried to make a spring boot service which receive multiple files uploaded by user, my service accept files as (Java) Multipart for its type;

First, i convert all multiparts into list of bytes array then running into this function
![image](https://user-images.githubusercontent.com/25737227/77402906-f42ed300-6de1-11ea-982b-c419b3c1e582.png)

That should return list of named streamable, which i use in below function to upload to ipfs:
![image](https://user-images.githubusercontent.com/25737227/77402957-0c9eed80-6de2-11ea-9783-5553e6b75031.png)

As we can see, i intend to wrap those files into 1 single directory which i can named;

Then i tested it using postman to upload 2 files, if the wrap flag is true, it returns 4 hash:

________ Automatically created directory (lets call this H1)
|____ My supposed to be directory (lest call this H2)
|____ My file 1 (lets call this H3)
|____ My file 2 (lets call this H4)

My target is 
________ H2
|____ H3
|____ H4

If wrap flag set to false, it returns 3 hash:
________ root directory
|____ H2
|____ H3
|____ H4

 Another thing is, when im uploading files using byteArrayWrapper, seems like i cannot retain its original filename, whilst uploading single file using dirWrapper works perfectly (correct directory structure and original filename retained after uploaded in ipfs)

**Comment by kevodwyer** [comment]
I attempted to replicate the above, but am not sure i understand the problem that you are seeing. Can you re-phrase?
I would not expect the individual filenames to be retained as they are not provided to the add api when uploading via DirWrapper.
Recently the new ipfs.files.write() method has been added to this client. That may be closer to your needs.

**Comment by kevodwyer** [comment]
Closing issue as stale. Feel free to re-open with new information.
