### ISSUE TITLE
Infura node as a client

### ISSUE THREAD

**Issue by kuabhish** [ipfs-shipyard/java-ipfs-http-client#158]
I am trying to connect to an Infura node from Java Android application.
I was following the issue to connect to an infura node. 

https://github.com/ipfs-shipyard/java-ipfs-http-client/issues/115
like this :
IPFS ipfs = new IPFS("/dnsaddr/ipfs.infura.io/tcp/5001/https");

But I am getting this error. 

```
java.lang.RuntimeException: IOException contacting IPFS daemon.
    Trailer: null ipfs method not allowed
```

Any suggestions please.

**Comment by kevodwyer** [comment]
closing as stale. Check out new release
