### ISSUE TITLE
使用ipfs 0.5.1 版本 java 调用出现如下问题

### ISSUE THREAD

**Issue by NDCFL** [ipfs-shipyard/java-ipfs-http-client#163]
![image](https://user-images.githubusercontent.com/32116003/82814498-df49eb00-9ec9-11ea-88ed-fdbf683a671b.png)

**Comment by NDCFL** [comment]
请问如何处理

**Comment by zyc751201** [comment]
你解决了么，我也是遇到相同的问题

**Comment by NDCFL** [comment]
我解决了

**Comment by zyc751201** [comment]
ndcfl，方便留一个加一个qq么？我的是271168735，你用ipfs是运用在那个场景呢？

**Comment by NDCFL** [comment]
可以，私聊 275300091

**Comment by odisseus** [comment]
Unfortunately I don't understand your language, but it seems that you're getting a HTTP code 405 when trying to use this library with an IPFS 0.5.x daemon. This issue is caused by a change in the server API (see #157 for details).  The workaround for this problem is using older versions of IPFS, namely 0.4.x.

**Comment by NDCFL** [comment]
Thank you, because I encountered 405 error when instantiating IPFs in use. Now it has been solved, thank you!






&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Myroslav"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 上午6:05
收件人:&nbsp;"ipfs-shipyard/java-ipfs-http-client"<java-ipfs-http-client@noreply.github.com&gt;;
抄送:&nbsp;"絮落锦乡"<275300091@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ipfs-shipyard/java-ipfs-http-client] 使用ipfs 0.5.1 版本 java 调用出现如下问题 (#163)





 
Unfortunately I don't understand your language, but it seems that you're getting a HTTP code 405 when trying to use this library with an IPFS 0.5.x daemon. This issue is caused by a change in the server API (see #157 for details).  The workaround for this problem is using older versions of IPFS, namely 0.4.x.
