### ISSUE TITLE
IPFS pin update returns a wrong type

### ISSUE THREAD

**Issue by odisseus** [ipfs-shipyard/java-ipfs-http-client#166]
The HTTP endpoint for updating pins returns a list of affected pin hashes. This is true for both versions 0.4.x and 0.5.x (I have actually checked versions 0.4.23 and 0.5.1).

However, the return type of the method `io.ipfs.api.IPFS.Pin#update` is a `List<MultiAddress>` instead of `List<Multihash>`.

**Comment by kevodwyer** [comment]
Are you able to point me to the documentation that specifies List<MultiAddress> ?
I found https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/PIN.md, but that doesn't mention pin.update

**Comment by odisseus** [comment]
My point was that the Java wrapper attempts to cast the actual result into a wrong type. It should have been a list of hashes, but the java method used to return a `List<MultiAddress>`.

Looks like this bug has been fixed in the commit 710c4edcd521d550e385c9ae51aa9a9da4b56aac.
