### ISSUE TITLE
null 405 - Method Not Allowed

### ISSUE THREAD

**Issue by los1992** [ipfs-shipyard/java-ipfs-http-client#178]
执行 这个的时候GoIPFS ipfs = new GoIPFS(projectProperties.getIpfsAddr()); 直接就是null 405 - Method Not Allowed 版本是v1.2.3

**Comment by lidel** [comment]
@los1992  v1.2.3 is too old  and unable to work with latest go-ipfs. That is why you get `405 - Method Not Allowed` error.

You need to update to  the latest version (v1.3.3 or later): 
https://github.com/ipfs-shipyard/java-ipfs-http-client/releases

**Comment by vpei** [comment]
我用http网址，把GET改成POST就行。像 curl -X POST http://127.0.0.1:5001/api/v0/swarm/peers 就正常，直接在浏览器用网址就出错。
