### ISSUE TITLE
How to read the content of a file?

### ISSUE THREAD

**Issue by QAInsights** [ipfs-shipyard/java-ipfs-http-client#180]
I am trying to implement IPFS in JMeter. I followed the steps in the README.md. But the below line is not showing up the file content. Could you please guide me?

```
Multihash filePointer = Multihash.fromBase58("QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB");
byte[] fileContents = ipfs.cat(filePointer);
```

**Comment by Clay-Ferguson** [comment]
you just need to convert the byte array to a string.
```
String s = new String(bytes, StandardCharsets.UTF_8);
```

**Comment by QAInsights** [comment]
Thanks @Clay-Ferguson 🙏
