### ISSUE TITLE
IOException contacting IPFS daemon

### ISSUE THREAD

**Issue by Sini0r** [ipfs-shipyard/java-ipfs-http-client#189]
i get a error :IOException contacting IPFS daemon.  when add a file to ipfs in linux . 
the same code run sucessfly in other system.

why this error produced , and how to solve it ?

thank you.

**Comment by Sini0r** [comment]
and i add a file by cmd ;  then java code it works.  maybe it causes by not run background ?

**Comment by mognify** [comment]
please provide the full error message
you can censor the site location if it's referenced in the message
