### ISSUE TITLE
Looking for a maintainer familiar with Java! 🙏

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/java-ipfs-http-client#194]
This project needs a maintainer that will ensure this library works with Kubo RPC (https://docs.ipfs.tech/reference/kubo/rpc/)

Kubo team will be maintaining [GO](https://github.com/ipfs/kubo/issues/9124) and [JS](https://github.com/ipfs/kubo/issues/9125) libraries, but we need someone familiar with Python to step up and help with this one.

If you are interested, please comment below.

**Comment by ianopolous** [comment]
Hi @lidel , autonome and I are in the process of arranging for us to update this library.

**Comment by lidel** [comment]
@ianopolous was this resolved?
Asking because  I see this library is still testing against Kubo 0.15 while we released 0.16 a while ago

**Comment by mognify** [comment]
this project seems interesting, and i think it's necessary for my own project, so i'll pitch in to bring it up to par
