### ISSUE TITLE
mvn test fails with java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by adpadilla** [ipfs-shipyard/java-ipfs-http-client#195]
I  attempted to run the tests (both Mac/Linux envs) with ipfs running via docker compose script provided but receive a 'read timed out' error when tests were running. Please advise. 

Git Hash(master branch) used: f757426b6ae77419742f9ab1620f29db12881375

java.net.SocketTimeoutException: Read timed out

**Comment by Clay-Ferguson** [comment]
probably just needs this:

```java
HttpURLConnection c = (HttpURLConnection)url.[openConnection](https://www.tabnine.com/code/java/methods/java.net.URL/openConnection)();
  c.[setReadTimeout](https://www.tabnine.com/code/java/methods/java.net.HttpURLConnection/setReadTimeout)(TIMEOUT);
  c.[setConnectTimeout](https://www.tabnine.com/code/java/methods/java.net.HttpURLConnection/setConnectTimeout)(TIMEOUT);
```

**Comment by ianopolous** [comment]
The docker compose script was out of date. Tests are green on the latest master.
