### ISSUE TITLE
 java-ipfs-http-client-v1.3.3 cannot support base1 encoding for ipfs v0.15.0

### ISSUE THREAD

**Issue by tealover** [ipfs-shipyard/java-ipfs-http-client#198]
I install IPFS with docker-compose and the version of IPFS is 0.15.0. After "ipfs init" , IPFS echo peerID is "12D3KooWKKBtGFyA3udwR6Pkyyg1qjsdjcgRTNcQrr1HNxsLNAAX", it seems not be base58 encoding. Th java client with java-ipfs-http-client-v1.3.3 cannot parse the PeerID and ipfs.bootstrap.add fails too. The error message is "java.lang.IllegalStateException: Unsupported base encoding: Base1"
Should java-ipfs-http-client need to update for ipfs-v0.15.0??

the unit test case show bellow :
`MultiAddress addr = new MultiAddress("/ip4/172.24.1.93/tcp/4001/p2p/12D3KooWKd5e3G1oBoFMwBQugCn5diUW1DaiqFStSemJJNhRnv9R");
            ipfs1.bootstrap.add(addr);`

**Comment by ianopolous** [comment]
This is fixed in master. so you can either use that or wait for a new release.
