### ISSUE TITLE
is v1.3.4 release coming?

### ISSUE THREAD

**Issue by ladaspcsn** [ipfs-shipyard/java-ipfs-http-client#201]
Hi, I noticed that you merged some pull requests with fixes recently. Are you planning on releasing the changes? 
Thanks in advance

**Comment by kevodwyer** [comment]
Yes,
Targeting compatibility with kubo v0.17.0 - https://docs.ipfs.tech/reference/kubo/rpc/

**Comment by ladaspcsn** [comment]
Got it, thanks for the prompt response!
