### ISSUE TITLE
When a large file is uploaded, the heap resources are not released

### ISSUE THREAD

**Issue by liry-code** [ipfs-shipyard/java-ipfs-http-client#220]
Hello, I would like to ask a question.
In the Springboot project, use threads to upload a file of about 2G in ipfs, after the file is uploaded and the thread ends. 

The old generation resources in the heap cannot be released and always exist in the old generation.

The dump file of the JVM stack information was reviewed by the tool, and it was found that the unreleased resources in the old zone may exist in the sun.net.www.http.PosterOutputStream class.

This is the operating environment information：
JAVA: 1.8
java-ipfs-http-client: 1.3.3

Dump log analysis：

![image](https://user-images.githubusercontent.com/13272700/224339436-b0d64e46-af75-4a3b-8327-df8329c47667.png)

![image](https://user-images.githubusercontent.com/13272700/224339281-83d09bed-81d4-40b3-9a16-1c830a9463fa.png)

![image](https://user-images.githubusercontent.com/13272700/224339547-1f04d2cb-3de5-46ad-b3ab-5cd1899b2adc.png)

![image](https://user-images.githubusercontent.com/13272700/224339717-1b1e815a-4f72-4ec2-b4a1-f5d6d922669e.png)

![image](https://user-images.githubusercontent.com/13272700/224339762-275e52aa-4fdc-4236-ab16-7c81fb7b986b.png)

Expecting a reply ！

**Comment by kevodwyer** [comment]
Are you able to provide a minimal test case that demonstrates the problem? In the stacktrace i can only see a 1 line reference to io.ipfs.api.Multipart.finish()

**Comment by liry-code** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
