### ISSUE TITLE
javadoc

### ISSUE THREAD

**Issue by cinterloper** [ipfs-shipyard/java-ipfs-http-client#4]
Hey
Is there any javadoc associated with this project?

**Comment by ianopolous** [comment]
Not at the moment, but I intend to write some. In the meantime, there is only one source file you need (org.ipfs.api.IPFS) which is very readable.

**Comment by kevodwyer** [comment]
Closing as stale. The unit tests are a good place to start to see usage of api. Addtional documentation will appear soon
