### ISSUE TITLE
MerkelNode is not functioning as intended anymore (solved?)

### ISSUE THREAD

**Issue by cybershrapnel** [ipfs-shipyard/java-ipfs-http-client#48]
Note: I have mostly solved this issue now

I have followed along with several examples and tested with old .jar releases.

The function below no longer works as it use to and I can't figure out what the new implementation is supposed to be...

MerkleNode addResult = new MerkleNode(ipfs.add(file));

This function seems to want a string now....but it doesn't...and it thinks the MerkelNode is a list that is not compatible and won't let me cast it. But I'm probably doing something or overlooking something obvious.

I'm also having erroneous errors the below if I make a new project using the newest .jar but it works if I use an old project that was built from the old maven stuff.???? by that I mean I delete the dependency from old project and import the new .jar and it magically works fine.
ipfs.refs.local();

Quite frankly, I'm really at a loss here? Is everything working as intended? Could you possibly release a full example project to let us build off of and see working...

Note that I was able to build and compile the master build from download, And I will do some more testing from here. maybe the .jar was an improper or old build that was included in your last push. As I can see it is clearing working when running the API test....

Thanks!!! Great work btw.

update:
I was finally able to figure this out. I copy and pasted the actual source into my packages instead of using a dependency and then I loaded all the dependencies from your original jar as dependencies to my project directly. Everything seems fine now.

But the MerkleNode has definetly changed!

This is the new formatting if anyone needs to know :)

MerkleNode addResult = ipfs.add(file).get(0);
or
MerkleNode file2 = ipfs.add(new NamedStreamable.ByteArrayWrapper("Some data".getBytes())).get(0);

Here is the current code I was playing with that successfully posted a file to the cloud...and was retrievable via my ipfs node through command prompt.

    package rotatewheel;

    import io.ipfs.multihash.Multihash;
    import java.io.*;
    import java.nio.file.*;
    import java.util.*;
    import io.ipfs.api.*;
    import io.ipfs.multiaddr.MultiAddress;
    import java.io.File;
    import java.io.IOException;

    public class ipfstest {

    public File ifFile = null;

    public void whatfile(File file) {
        ifFile = file;
        ifFile = new File("C://i.mp3");   //comment out this line in production   
        launch();
    }

    private void launch() {

        IPFS ipfs = new IPFS(new MultiAddress("/ip4/127.0.0.1/tcp/5001"));
        System.out.println("Connected");

        try {
            System.out.println("hostfile test");
            NamedStreamable hostFile = null;
            File holdFile = null;
            if (ifFile == null) {
                Path tempFile = Files.createTempFile("IPFS", "tmp");
                BufferedWriter w = new BufferedWriter(new FileWriter(tempFile.toFile()));
                w.append("My Data is Kenny22gdfgd.");
                w.flush();
                w.close();
                hostFile = new NamedStreamable.FileWrapper(tempFile.toFile());
                holdFile = tempFile.toFile();
            } else {
                hostFile = new NamedStreamable.FileWrapper(ifFile);
            }
            NamedStreamable file = hostFile;

         
            System.out.println("pin test");
            MerkleNode file2 = ipfs.add(file).get(0);

            Multihash hash = file2.hash;
            System.out.println(file2.hash + "hash: ");
            Map<Multihash, Object> ls1 = ipfs.pin.ls(IPFS.PinType.all);
            boolean pinned = ls1.containsKey(hash);
            List<Multihash> rm = ipfs.pin.rm(hash);
            List<Multihash> add2 = ipfs.pin.add(hash);
            List<Multihash> add3 = ipfs.pin.add(hash);
            Map<Multihash, Object> ls = ipfs.pin.ls(IPFS.PinType.recursive);
            ipfs.repo.gc();
            Map<Multihash, Object> ls2 = ipfs.pin.ls(IPFS.PinType.recursive);
            boolean stillPinned = ls2.containsKey(hash);
        } catch (IOException er) {
        }
        System.out.println("file put done: ");
    }

    public static void main(String[] args) {
        ipfstest app = new ipfstest();
        //app.launch();
        app.whatfile(null);
    }

    private IPFS ipfs;
    }

**Comment by ianopolous** [comment]
Hi @cybershrapnel, 
Glad to hear you've mostly got it working. ipfs.add returns a list of merklenodes, so no need to explicitly call the merklenode constructor. This is because depending on the options it can return more than one. For example if you tell it to wrap the file in a directory it will return two. I will update the readme to reflect the change.

**Comment by cybershrapnel** [comment]
yes, I am figuring it out, slowly but surely... I wish I had more documentation...But the source code of course is all you need with time :) haha

I updated the code above after you posted I think...Look it over and tell me where I am being proper.. and improper.  This works just fyi...

I'm incorporating this into the nanocheeze.com app btw.... I'm going to use it for the gridware apps download as a primary download and switch http which i currently use to secondary, and eventually I am going to integrate my Quantum NanoCompression algorithm with IPFS to store hash recreation values.  Basically a giant worldwide cloud of hash values and their corresponding data(s) and then a map to put files back together using the stored hashes. If you are curious, I posted the code to this on my github, it is a part of the nanocheeze app. If I can figure out a way to properly store the values throughout ipfs with a little help of course, you should see a file compression size of 32:1

**Comment by cybershrapnel** [comment]
I'm curious if you can help me with another small issue I ran into. I feel ashamed as I should be able to do this myself lol.

So I worked this api into my current downloading classes. I have a progress bar that shows your http download to the user as the file downloads. Now, if your pc is running IPFS it will download via IPFS instead of http... This works great!!

But I ran into a problem with buffer the byts from IPFS. I am already bye buffering the http stream so that it saves to a randomaccessfile just beautifully. But I cannot get the IPFS stream to do the same. It wants to send it to that api as one giant byte array. 

This of course causes a memory failure on behalf of the byte array. I can work around this for the most part by increasing the VM memory heap with the xmx commands, but that is not the way I want to go obviously. But I was not able to upload nor download a 70+ megabyte file with standard VM settings. But with xmx1024 option I seem to have pretty much no problem except with really big files of course....

If you have a chance, can you show me a buffered byte array example of getting a file from the IPFS cloud. sorry to be a bother. I;m just stoked I got this working.... Everything in my app now grabs from IPFS before http :)

**Comment by kevodwyer** [comment]
Closing as stale. Free free to re-open if required
