### ISSUE TITLE
directory Test on Windows System seems wrong

### ISSUE THREAD

**Issue by 18916204759** [ipfs-shipyard/java-ipfs-http-client#49]
When i run the directory test on windows, it return like this "DIR14930592264188763745\abcd\3.jpg", it's not a directory, but a file name, under unix/linux, it's work ok. Just can get like this "DIR14930592264188763745/abcd/3.jpg", what should i do ?
![qq 20171117102915](https://user-images.githubusercontent.com/13064703/32926448-312df204-cb82-11e7-987f-4638fbdb7498.png)

**Comment by kevodwyer** [comment]
This is resolved in latest version
