### ISSUE TITLE
[pubsub] Resubscribe when losing connection/Reactive Stream support

### ISSUE THREAD

**Issue by theborakompanioni** [ipfs-shipyard/java-ipfs-http-client#66]
I currently encounter a problem when being subscribed to a topic and the ipfs nodes goes down.
Consumer threads blocks indefinitely (as intended) as no more elements are pushed into the queue.
Is there any reasonable way to handle such situations?

I have wrapped all calls to `sub` to return a Reactive Stream but I have no way of detecting EOF.
Here is a quick example (note the missing `complete` call):
```java
Flux<Map<String, ?>> ipfsMessageFlux = Flux.create(fluxSink -> {
    try {
        Supplier<Object> sub = ipfs.pubsub.sub(topic);

        while (true) {
            Object o = sub.get();
            if (fluxSink.isCancelled()) {
                return;
            }

            if (o != null) {
                if (Map.class.isAssignableFrom(o.getClass())) {
                    Map<String, ?> map = (Map<String, ?>) o;
                    fluxSink.next(map);
                } else {
                    log.warn("Refuse to emit message - object not of instance Map: {}", o);
                }
            }

            if (fluxSink.isCancelled()) {
                return;
            }
        }
    } catch (Exception e) {
        fluxSink.error(e);
    }
});
```
What do you think about returning a Flux ([project reactor](https://projectreactor.io/)) or an Observable ([rxjava](https://github.com/ReactiveX/RxJava)) in `Pubsub`? Then we'd be able to signal the end of the stream. Would something like this fit the projects roadmap? I'd be very happy to provide a pull request.

**Comment by ianopolous** [comment]
Very good question! Thanks for trying it out! I've just pushed an improved api to master that returns CompletableFutures, which allows you to handle any errors correctly. I prefer not to import any external libraries here. Could you try it out?

**Comment by theborakompanioni** [comment]
@ianopolous Thanks for the unbelievably fast reply. I'll try it and report back.

**Comment by theborakompanioni** [comment]
Current solution falls back to blocking mode when no item has been emitted e.g. when using `get(long, TimeUnit)` with timeout on the returned `CompletableFuture` (as no further item is pushed in the queue).

Also, if simply using the blocking `get()` it somehow does not work at all anymore.
I have previously been using the latest stable release of `v1.2.0` which worked.

**Comment by ianopolous** [comment]
Hmm it worked in the few tests I tried. Could you show me your code?

**Comment by ianopolous** [comment]
Actually, I just realised I'm testing on ipfs version 0.4.14-rc3. So that may be another requirement.

**Comment by theborakompanioni** [comment]
Hey @ianopolous. 
I have now uploaded changes to reproduce the breaking behaviour: https://github.com/theborakompanioni/mesqueteltra/commit/00a445387d22003258a1a42b7fc6fdc06feb75cd?diff=split

I have since switched to ipfs `v0.4.14`: The commit before works - the above changes break the functionality. Cannot quite tell you why :/

In the repo above I am more or less just playing around - expect rather messy code. The idea is to have two mqtt clients playing ping pong over two mqtt broker which are connected over ipfs.

**Comment by theborakompanioni** [comment]
Any updates on this? Is there any way I can help?

**Comment by ianopolous** [comment]
Sorry for the delay. As far as I can see from that code it should work. What exactly is happening?

**Comment by ianopolous** [comment]
One thing to be careful of is there is no buffer in ipfs. Subs only receive things published "after" the sub has completed. You'll note in my test for this I had to wait 100ms between the sub and the pub to ensure that it worked.

**Comment by theborakompanioni** [comment]
Thanks for your answer @ianopolous. 

As far as I understand there might be some problems with `retrieveAndParseStream`.
```java
private Supplier<CompletableFuture<Object>> retrieveAndParseStream(String path, ForkJoinPool executor) throws IOException {
        BlockingQueue<CompletableFuture<byte[]>> futures = new LinkedBlockingQueue<>();
        CompletableFuture<byte[]> first = new CompletableFuture<>();
        futures.add(first);
        executor.submit(() -> getObjectStream(path,
                res -> {
                    futures.peek().complete(res);
                    futures.add(new CompletableFuture<>());
                },
                err -> {
                    futures.peek().completeExceptionally(err);
                    futures.add(new CompletableFuture<>());
                })
        );
        return () -> {
            try {
                return futures.take().thenApply(arr -> JSONParser.parse(new String(arr)));
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        };
    }
```
When you wait 100ms initially everything might look fine. Without it, `futures.take()` will clear the queue before the callback can execute `futures.peek().complete(res)` or `futures.peek().completeExceptionally(err)`. (I dont exactly understand the "race condition" comment in the tests [R415](https://github.com/ipfs/java-ipfs-api/commit/3c186639f64e64af9204887e5ce9b90d54e3be8d#diff-7fa9ead50e7aaf8a2a1beb65eb3fb2fdR415))

But, how can one now know, when to call the suppliers `get` method again? The `CompletableFuture` will never be picked up by the callback again and therefore never complete for the same reasons as stated above. I would have to know in advance when the next message arrives for the callback to use my future with `futures.peek()`.

Any thoughts?

**Comment by ianopolous** [comment]
I've just pushed a new pubsub api to master which fixes a few issues, but I can't fix the ipfs race condition. There is no happens before relationship in ipfs between subbing to a topic and pubbing to it.

**Comment by ianopolous** [comment]
I've just pushed another fix which totally resolves the issue. The potential race condition was on my end, not in ipfs.

**Comment by kevodwyer** [comment]
Closing issue as stale. Feel free to re-open will more detail if required
