### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space when adding file

### ISSUE THREAD

**Issue by segator** [ipfs-shipyard/java-ipfs-http-client#72]
When adding a "large" file of 100M got this error

SO Windows

`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at sun.net.www.http.PosterOutputStream.write(PosterOutputStream.java:78)
	at io.ipfs.api.Multipart.addFilePart(Multipart.java:102)
	at io.ipfs.api.IPFS.add(IPFS.java:83)
	at io.ipfs.api.IPFS.add(IPFS.java:74)
	at io.ipfs.api.IPFS.add(IPFS.java:70)
`
` IPFS ipfs = new IPFS("/ip4/127.0.0.1/tcp/5001");    
        NamedStreamable streamable = new NamedStreamable.FileWrapper(new File("D:\\testfile"));
        List<MerkleNode> addParts = ipfs.add(streamable);`

**Comment by avanaur** [comment]
Having this issue as well.

Seems to be fixed if to add `httpConn.setChunkedStreamingMode(1024 * 1024 * 10);` on `Multipart` contructor

**Comment by Moosheimer** [comment]
Is that already solved? I have this problem too.

**Comment by Clay-Ferguson** [comment]
Just a tip: Normally a stream buffer size for web traffic doesn't really benefit from being larger than 4096 (on the setChunkedStreamingMode call), so when you go larger you're potentially just wasting memory, rather than speeding things up.

**Comment by avanaur** [comment]
Yeah, I

> Just a tip: Normally a stream buffer size for web traffic doesn't really benefit from being larger than 4096 (on the setChunkedStreamingMode call), so when you go larger you're potentially just wasting memory, rather than speeding things up.

Yeah I agree. I do not remember this problem clearly. I think without the chunk streaming mode, it is not buffering and sort of loading the whole file in-memory, thus OOM eventually. 

Smaller chunks would probably work.

**Comment by Moosheimer** [comment]
Very good point. I tried it with a size of 16KB and it works fine. No more OOM. 
If this is of course useless, then I will reduce it to 4KB.
It would still be great if this little adjustment finds its way into the official release, because I don't like to keep a shadow copy.

**Comment by Clay-Ferguson** [comment]
@avanaur yeah with any kind of file transfers or streaming in Java you have to be sure there's absolutely nowhere in the handling that there's a byte array being used, or it will blow up memory on massive files for sure. 

Also there's more to the 4096 number than just a suggested number. The streaming apis buffer sizes at the lower levels of networking system code all use 4096, so everyone uses that size for any internet streaming because everything lines up perfectly with no unnecessary buffering or waiting. 4096 is widely accepted as the best number in most cases.
