### ISSUE TITLE
Add timeout for http connections and transfer

### ISSUE THREAD

**Issue by romainreuillon** [ipfs-shipyard/java-ipfs-http-client#88]
Dear devs,

the present IPFS Java API doesn't seem to accept connection, transfer and wait timeout. This might be needed when communicating with remote IPFS nodes. Is there any plan to implement that ?

(In order to achieve that properly in some libs of mine, I had to move from the native http functionalities of the one in the java lib to [apache http client](https://hc.apache.org/))

Cheers,
Romain

**Comment by odisseus** [comment]
I believe this issue has been fixed by PR #147.

**Comment by kevodwyer** [comment]
read and connection timeout has now been implemented. closing as resolved
